### PR TITLE
Enhanced the login form and sign up form

### LINKED ISSUE #28: Feat:Enhance Sign up and Login Page
### Describe the feature

Enhancing the UI of pages without deleting any logic or data

### Add ScreenShots

image

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by devxMani**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ... Icons, Transitions , Effects
  - Fixes ... Sign up and Login form
  - Updates ... 

### Related Issues
Link any related issues using the format `Fixes #issue_number`.
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #28 "

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ... Login form and Sign up form
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)

https://github.com/user-attachments/assets/9fd32abb-fc91-4a5b-8303-eb9221f7410a

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC-Extended

### CODE REVIEW

**Review by Prithwi32 — COMMENTED** [review]
@devxMani LGTM 👍

**Comment by devxMani** [comment]
@Prithwi32 Hi, Can I work on These pages more in the new PR I can add more things to this and can you tell me why the login and sign-up feature not working...

**Comment by devxMani** [comment]
@Prithwi32 Are you on DC ( discord ) ?

**Comment by Prithwi32** [comment]
> @Prithwi32 Are you on DC ( discord ) ?

Yes @devxMani ..
u can search me as _ prithwi_

**Pull request merged**
