### PR TITLE
Feat: Add Issue, PR Templates

### PR DESCRIPTION
**Pull request by Prithwi32**

### CODE REVIEW

**Comment by Prithwi32** [comment]
@Dbrightson Issue and PR templates added..could u check out

**Comment by Dbrightson** [comment]
Looks good @Prithwi32 . Thanks for the contribution

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @Dbrightson 
Regards ,
Community Manager gssoc-ext

**Comment by Dbrightson** [comment]
@AKSHITHA-CHILUKA Added the level labels as requested, Thank you!

**Comment by AKSHITHA-CHILUKA** [comment]
Thanks @Dbrightson

**Pull request merged**
